### ISSUE TITLE
Licensing information

### ISSUE THREAD

**Issue by rachitnigam** [dillonhuff/ahaHLS#3]
Are there plans for open sourcing this tool under a permissive commercial license (MIT, BSD)? If there is already a license, can you point me to it?

**Comment by dillonhuff** [comment]
@rachitnigam my plan was to license it as MIT or just put it in the public domain. Do you have a preference?

**Comment by rachitnigam** [comment]
MIT would probably work fine! 

Thanks for the quick response and working on this tool! We are considering using this in conjunction with CoreIR for a typed HLS language (https://github.com/cucapra/seashell) and would like to have things be open source.

**Comment by dillonhuff** [comment]
Looks interesting!

I just added the MIT license to the repo.

Let me know if you have other questions getting the system working.
